### PR TITLE
timer overlay on lc problem

### LINKED ISSUE #38: Implement Countdown Timer overlay into Leetcode Problem pages
**Is your feature request related to a problem? Please describe.**
As someone practicing leetcode problems, I want to save time and not spend too much on a single problem.

**Describe the solution you'd like**
I want a countdown timer that runs down on the problem page while I'm working, to remind me when to finish with my current problem.

**Describe alternatives you've considered**
Timer in the chrome extension?

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by JackLiX0105**
### Issue Ticket Number and Link
#38
### Reason of Changes
Initial basic timer on LC problems
### Testing
To be done
### Checklist

- [ ] All tests pass locally.
- [ ] Code is self-documented or comments have been added where necessary.
- [ ] New code follows the project's coding style and guidelines.
- [ ] Relevant documentation has been updated (e.g., README, Wiki).

---

### CODE REVIEW

**Comment by jgetzel** [comment]
testing should be in the test folder, and be called timer.test.js (I think the .test.js part is important for jest to detect/run the test)

**Comment by jgetzel** [comment]
I added test file to test folder plus renamed so it would get run. It crashes now tho

**Review by Brian-MT-Nguyen — APPROVED** [review]
Timer functionality mostly there, we could potentially add better css styling to it, make it draggable, maybe refactor but functionality and structure is good as is.

**Comment by jgetzel** [comment]
Tests are failing because you're changing jest config in a weird way. Revert back to the upstream jest config in dev, they're functionally identical to what you're trying to do

**Pull request merged**
